---
title: "Data Wrangling"
author: "Ben Moolman"
date: "2023-09-05"
output: html_document
---

```{r}
library(tidyverse)
```


```{r}
data <- readr::read_csv("https://raw.githubusercontent.com/JeffSackmann/tennis_atp/master/atp_matches_2023.csv")
```

How to get the pivot longer to work
```{r}
# toy df
cols <- c("p1", "p2",
          "p1_srv_won", "p1_srv_lost",
          "p2_srv_won", "p2_srv_lost")
values <- c("A", "B", 96, 26, 72, 40)
toydf <- data.frame(cols, values) |> pivot_wider(names_from = cols, values_from = values)

# now trying pivot longer to extend columns
toydf |> pivot_longer(cols = c("p1_srv_won", "p2_srv_won"), 
               names_to = "service_point", values_to = "srv_won")

toydf <- toydf |> pivot_longer(cols = c("p1_srv_won", "p1_srv_lost", "p2_srv_won", "p2_srv_lost"),
                      names_to = "won_point", values_to = "server") |>
  mutate(pt_winner = recode(
    won_point,
    "p1_srv_won" = 1,
    "p1_srv_lost" = 0,
    "p2_srv_won" = 0,
    "p2_srv_lost" = 1)) |>
  mutate(pt_server = recode(
    won_point,
    "p1_srv_won" = 1,
    "p1_srv_lost" = 1,
    "p2_srv_won" = 0,
    "p2_srv_lost" = 0))
  
toydf <- uncount(toydf, weights = as.numeric(server))
toydf |> select(1,2,6,5)
```


```{r}
columns <- data |> select(1:3,6,7,9,11,17,19,24,30,32,33,39,41,42,46,48) |> 
  mutate(w_svpt_w = w_1stWon + w_2ndWon,
         w_svpt_l = w_svpt - w_svpt_w,
         l_svpt_w = l_1stWon + l_2ndWon,
         l_svpt_l = l_svpt - l_svpt_w) |>
  select(winner_name, loser_name, w_svpt_w, w_svpt_l, l_svpt_w, l_svpt_l, match_num,
         1:5, 7, 9, 16:17)
columns


test <- columns |> pivot_longer(cols = c("w_svpt_w", "w_svpt_l", "l_svpt_w", "l_svpt_l"),
                        names_to = "won_point",
                        values_to = "server") |>
  mutate(pt_winner = recode(
    won_point,
    "w_svpt_w" = 1,
    "w_svpt_l" = 0,
    "l_svpt_w" = 0,
    "l_svpt_l" = 1)) |>
  mutate(pt_server = recode(
    won_point,
    "w_svpt_w" = 1,
    "w_svpt_l" = 1,
    "l_svpt_w" = 0,
    "l_svpt_l" = 0)) |>
  # remove rows where server is NA (walkovers)
  filter(!is.na(server))

test <- uncount(test, weights = as.numeric(server)) |>
  # get rid of server column and won_point column
  select(-server, -won_point) |>
  # reorganize columns
  select(winner_name, loser_name, pt_winner, pt_server, everything())
```

Exploring serving percentages to make sure they are correct
```{r}
# test |> group_by(match_num, winner_name, loser_name, pt_server) |> 
  # summarise(total_served_points = sum(pt_server),
    # total_won_points = sum(pt_winner),
    # percentage_won = (total_won_points / total_served_points) * 100)


# Look at winner of matches win percentage of points on their serve
test |> group_by(winner_name, loser_name, match_num) |>
  filter(pt_server == 1) |> summarise(perc = mean(pt_winner))

# Look at loser of matches win percentage of points on their serve
test |> group_by(winner_name, loser_name, match_num) |>
  filter(pt_server == 0) |> summarise(perc = 1 - mean(pt_winner))

data |> filter(match_num == 100)
```

