---
title: "Forming_Prior_Dist"
author: "Ben Moolman"
date: "2023-11-16"
output: html_document
---

```{r}
# Put relevant csv files in a vector
ext_vec <- c("atp_matches_2021.csv",
             "atp_matches_2022.csv",
             "atp_matches_2023.csv")

# Function to read in csv files
atp_21_23 <- purrr::map(ext_vec, read_matches) |>
  bind_rows()

# Only select rows that have point data
atp_21_23 <- atp_21_23 |> filter(!is.na(w_svpt))
```

```{r}
# Create a dataframe with only the columns we need
atp_21_23 <- atp_21_23 |>
  select(tourney_id,
         tourney_name,
         surface,
         winner_name,
         loser_name,
         w_svpt,
         w_1stWon,
         w_2ndWon,
         l_svpt,
         l_1stWon,
         l_2ndWon)

# Create new variables to measure total points won
atp_21_23 <- atp_21_23 |>
  mutate(w_srv_w = w_1stWon + w_2ndWon,
         w_srv_l = w_svpt - w_srv_w,
         l_srv_w = l_1stWon + l_2ndWon,
         l_srv_l = l_svpt - l_srv_w)


piv_longer <- atp_21_23 |> pivot_longer(cols = c("w_srv_w", "w_srv_l", "l_srv_w", "l_srv_l"),
                      names_to = "won_point", values_to = "server") |>
  mutate(pt_winner = recode(
    won_point,
    "w_srv_w" = 1,
    "w_srv_l" = 0,
    "l_srv_w" = 0,
    "l_srv_l" = 1)) |>
  mutate(pt_server = recode(
    won_point,
    "w_srv_w" = 1,
    "w_srv_l" = 1,
    "l_srv_w" = 0,
    "l_srv_l" = 0))
  
piv_longer <- uncount(piv_longer, weights = as.numeric(server))

current_df <- piv_longer |> select(1:5, 14, 15)
```

```{r}
```



```{r}
```


             


  
  